### ISSUE TITLE
Potential security breach.

### ISSUE THREAD

**Issue by agood-boy** [paperbits/paperbits-styles#6]
Potential security breach. Google Cloud API Key in Url in file [/src/workshops/googleFonts/googleFonts.ts](https://github.com/paperbits/paperbits-styles/tree/master/src/workshops/googleFonts/googleFonts.ts)

You should recycle your credenttials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Hope this will be helpful to you！

shout me a coffee ☕️ via [PayPal](https://www.paypal.me/agoodboy)

<a href="https://www.paypal.me/agoodboy">
  <img width="160" height="41" src="https://raw.githubusercontent.com/DWilliames/paddy-sketch-plugin/master/.images/paypal-badge.png" >
</a>

**Comment by azaslonov** [comment]
Hi @agood-boy, thanks for reporting the leak, we'll address it. 

(P.S. I tried to send you "a coffee", but it asks for your Last Name and Country. Feel free to shoot me an email)
